// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2oP9P7p2rUEXTMwjXDHyjOrfMAPxsFv0',
    appId: '1:364731760131:web:fe29221b72be8595021836',
    messagingSenderId: '364731760131',
    projectId: 'refine-journal-2026',
    authDomain: 'refine-journal-2026.firebaseapp.com',
    storageBucket: 'refine-journal-2026.firebasestorage.app',
    measurementId: 'G-L6RMXHLJ69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs3J6tmn4O6ycYKxuSOR4nhj_ePTHPtOw',
    appId: '1:364731760131:android:033c1175f3acab38021836',
    messagingSenderId: '364731760131',
    projectId: 'refine-journal-2026',
    storageBucket: 'refine-journal-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqCabIeoxS0Gy98CL1xaSLf1FdC-4hxck',
    appId: '1:364731760131:ios:9d8a90cea5243003021836',
    messagingSenderId: '364731760131',
    projectId: 'refine-journal-2026',
    storageBucket: 'refine-journal-2026.firebasestorage.app',
    iosBundleId: 'com.bourasi.notesAppSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqCabIeoxS0Gy98CL1xaSLf1FdC-4hxck',
    appId: '1:364731760131:ios:9d8a90cea5243003021836',
    messagingSenderId: '364731760131',
    projectId: 'refine-journal-2026',
    storageBucket: 'refine-journal-2026.firebasestorage.app',
    iosBundleId: 'com.bourasi.notesAppSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2oP9P7p2rUEXTMwjXDHyjOrfMAPxsFv0',
    appId: '1:364731760131:web:9ff1c5f0e7411020021836',
    messagingSenderId: '364731760131',
    projectId: 'refine-journal-2026',
    authDomain: 'refine-journal-2026.firebaseapp.com',
    storageBucket: 'refine-journal-2026.firebasestorage.app',
    measurementId: 'G-155LPKTPZE',
  );
}
